name: pg_data
services:
  postgres:
    image: postgres:13
    env_file:
      - ../.env
    ports:
      - "5432:5432"
    restart:
      always
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
    driver: local